name: Makeobj Windows

on:
  push:
    tags:
      - 'Nightly'

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v1

    - name: compile makeobj
      run: |
        libs\buildTool\MSBuild\Current\Bin\MSBuild.exe Makeobj-Extended.vcxproj -property:Configuration=Release

    - name: zip result
      run: |
        Add-Type -AssemblyName System.IO.Compression.FileSystem
        [System.IO.Compression.ZipFile]::CreateFromDirectory("build\makeobj\Release\Makeobj-Extended.exe", "build\makeobj\Release\makeobj-extended_windows-nightly.zip")

    - name: Update binaries of Nightly Release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/makeobj/Release/makeobj-extended_windows-nightly.zip
        asset_name: makeobj-extended_windows-nightly.zip
        tag: Nightly
        overwrite: true
